# Generated by Django 2.2.2 on 2019-06-23 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190623_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 12, 39, 59, 509948, tzinfo=utc), verbose_name=datetime.datetime(2019, 6, 23, 12, 39, 59, 509948, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(upload_to='user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 23, 12, 39, 59, 508947, tzinfo=utc)),
        ),
    ]
